config/routes.rb
Rails.application.routes.draw do
  resources :teams

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'home/index'
  
  root to: "home#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    can :read, :all
    
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin_ability.rb
# in models/admin_ability.rb
class AdminAbility
  include CanCan::Ability
  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin
      can :manage, :all   
    end
   end
end

app/models/position.rb
class Position < ActiveRecord::Base
  has_many :user_positions
  has_many :users, :through => :user_positions
end

app/models/team.rb
class Team < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_positions
  has_many :positions, :through => :user_positions
  accepts_nested_attributes_for :positions
end

app/models/user_position.rb
class UserPosition < ActiveRecord::Base
  belongs_to :user
  belongs_to :position
  accepts_nested_attributes_for :position
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters, :only => [:create, :update]
  def new
    @positions = Position.all()
    super    
  end

  def create
    build_resource(sign_up_params)
    resource.legacy_password = params[:user][:password]
    resource_saved = resource.save
    yield resource if block_given?
    if resource_saved
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end     
  end

  def update
    @user = User.find(current_user.id)
    successfully_updated = @user.update_without_password(devise_parameter_sanitizer.sanitize(:account_update))
    if successfully_updated
      set_flash_message :notice, :updated
      # Sign in the user bypassing validation in case his password changed
      sign_in @user, :bypass => true
      redirect_to after_update_path_for(@user)
    else
      render "edit"
    end
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :skill, :position_ids => []) }
      devise_parameter_sanitizer.for(:account_update)  { |u| u.permit(:username, :email, :password, :skill, :position_ids => []) }
    end

end 

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!
  def index
    @teams = Team.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/home/index.html.erb
<!-- FLEXSLIDER -->
<section class="flex-wrapper">
  <div id="slider" class="flexslider">
    <ul class="slides">
      <li>
        <div class="flex-title">
          <h3>Volleyball Tournament</h3>
          <p>A fundraising tournament to support Bill and Nicole Garrison in their pursuit of god's will in the missions field.</p>
        </div>
        <%= image_tag "logo.jpg" %>
      </li>
      <li>
        <div class="flex-title">
          <h3>Play Volleyball for a good cause!</h3>
          <p>$20 / person | Blind Draw | BBQ (weather permitting) or Pizza | Chinese Auction | 50 / 50 raffle | BAKE SALE!! </p>
        </div>
        <%= image_tag "photos/group3.jpg", :alt => "" %>
      </li>
      <li>
        <div class="flex-title">
          <h3>BBQ!! (Weather permitting)</h3>
          <p>We recognize that this is memorial day weekend and will be providing relatively cheap BBQ options as part of the fundraiser!!</p>
        </div>
        <%= image_tag "photos/bbq.jpg", :alt => "" %>
      </li>
    </ul>
  </div>
</section>
<div class="clear"></div>  
<!-- PAGE CONTAINER -->
<section class="pagecontainer">
    <h1>What is this all about?!</h1>
    <hr/>
    <!-- POST -->
    <article class="post">
      <figure>
        <%= image_tag "photos/dr_garrison.jpg", :alt => "Dominican Republic" %>      
        <figcaption>
          <h2>Dominican Republic Missions</h2>
        </figcaption>
      </figure>
      <p>
        My wife (Nicole Garrison) and I (William Garrison) are both solid believers in Christ who have been
        looking for gods path in our lives. We both have felt very strongly that god has been calling us to 
        the missions field.
      </p>
      <p>
        Recently it was announced that The Chapel (a church we like to volunteer for along with our own church ) 
        will be taking a mission trip to the Dominican Republic from June 21 - 28, 2014. God has opened a door 
        for us to partner with an organization called Score International in sharing our love for Jesus with the
        Dominican Republic. We will be facing many challenges starting with the language barrier, assisting the 
        missionaries, ministering to the locals, working within orphanages, and helping the churches spread the message
        of Jesus while meeting some of their health and physical needs. 
      </p>
      <p>
        My wife will be a registered nurse who will be helping in that capacity while I will be putting my god given talents (few though they may be ;)) to use. We both feel we have a lot to offer this group. 
        The price to go on this trip is 1800 / person. My wife and I are looking to pursue all of it through fundraising. 
        Thank you and god bless!!
      </p>
      <p>
        This fundraiser is going to be the core of all of our fundraising. Its a volleyball fundraiser but its also a bake sale / 
        chinese auction / bbq sale and 50 / 50 raffle. Please come join us for all the fun!
      </p>
      <p>
        William and Nicole Garrison
      </p>
    </article>
  <hr/>
</section>
<div class="clear"></div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Volleyball Fundraiser Registration</title>
    <!-- application css file -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if flash[:notice] %>
      <p class="alert notice"><%= flash[:notice] %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <% if flash[:warning] %>
      <p class="alert warning"><%= flash[:warning] %></p>
    <% end %>
    <%= render "shared/menu" %>
    <%= render "shared/header" %>

    <!-- MAIN CONTAINER -->
    <section class="maincontainer">
      <%= yield %>
      <!-- FOOTER -->
      <footer id="footer">   
        <div class="clear"></div>
        <!-- COPYRIGHT -->
        <div class="credits">© 2013 Garrison Development</div>
        <!-- SOCIAL ICONS -->
        <ul class="social-icons">
          <li>
            <a href="#">
              <%= image_tag "social-icons/facebook.png", :alt => "Facebook", :class => "social-icon" %>
            </a>
          </li>
          <li>
            <a href="#">
              <%= image_tag "social-icons/twitter.png", :alt => "Twitter", :class => "social-icon" %>
            </a>
          </li>      
        </ul>
      </footer>
      <!-- BACK TO TOP BUTTON -->
      <a href="#" class="back-to-top"></a>
    </section>    
    <!-- application js file -->
    <%= javascript_include_tag 'application' %>
    <!-- JS FILES -->
  </body>
</html>

app/views/shared/_header.html.erb
<!-- HEADER -->
<header id="header">
  <div class="logo">
    <%= image_tag "logo.png"  %>
    <span>Volleyball Tournament Fundraiser</span>
  </div>
</header>
<div class="clear"></div>
<!-- MAIN MENU -->      <!--
<section id="mainmenu-container">
  <a class="toggleMenu" href="#">Menu</a>
  <nav>
    <ul id="mainmenu">
      <li>
        <a href="index.html">
          <span>Homepage</span>
        </a>
      </li>

      <li>
        <a href="#">
          <span>Pages</span>
        </a>
        <ul>
          <li>
            <a href="club.html">
              <span>Our Club</span>
            </a>
          </li>
          <li>
            <a href="team.html">
              <span>Our Team</span>
            </a>
          </li>
          <li>
            <a href="features.html">
              <span>Features</span>
            </a>
          </li>
          <li>
            <a href="layout.html">
              <span>Layout</span>
            </a>
          </li>
          <li>
            <a href="fixtures.html">
              <span>Fixtures</span>
            </a>
          </li>
          <li>
            <a href="result.html">
              <span>Match Result</span>
            </a>
          </li>
          <li>
            <a href="#">
              <span>Dropdown</span>
            </a>
            <ul>
              <li>
                <a href="#">
                  <span>Item 1</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span>Item 2</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span>Item 3</span>
                </a>
              </li>
              <li>
                <a href="#">
                  <span>Item 4</span>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </li>
      <li>
        <a href="galleries.html">
          <span>Gallery</span>
        </a>
        <ul>
          <li>
            <a href="galleries.html">
              <span>Galleries</span>
            </a>
          </li>
          <li>
            <a href="single-gallery.html">
              <span>Single Gallery</span>
            </a>
          </li>
        </ul>
      </li>
      <li>
        <a href="blog.html">
          <span>Blog</span>
        </a>
        <ul>
          <li>
            <a href="blog.html">
              <span>Blog</span>
            </a>
          </li>
          <li>
            <a href="single-post.html">
              <span>Single Post</span>
            </a>
          </li>
        </ul>
      </li>
      <li>
        <a href="contact.html">
          <span>Contact</span>
        </a>
      </li>

    </ul>
  </nav>
</section>
      -->

app/views/shared/_menu.html.erb
<!-- SUB MENU -->
<section id="submenu-container">
  <a id="mobile-menu" href="#">SubMenu</a>
  <nav id="submenu">
    <ul>
      <li>
        <%= link_to "Home", root_path %>
      </li>
      <% if user_signed_in? %>
      <li>
        <%= link_to "teams", teams_path %>
      </li>
      <% end %>
    </ul>
  </nav>
  <!-- LOGIN MENU -->
  <nav id="submenu-login">
    <ul>
      <% if user_signed_in? %>
        <li>
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> 
        </li>
      <% if current_user.admin? %>
	<li>
          <%= link_to 'Admin Dashboard', rails_admin.dashboard_path, :class=> 'navbar-link' %>
	</li>
      <% end %>
        <li>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        </li>
      <% else %>
        <li>
          <%= link_to "Register for Tournament", new_user_registration_path, :class => 'navbar-link'  %>
        </li>
        <li>
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>  
        </li>  
      <% end %>
    </ul>
  </nav>
</section>
<div class="clear"></div>